project:
  type: website
  render:
    - "*.ejs"
    - "*.qmd"
    - "*.ipynb"
    - "!sandbox/"

website:
  title: "Econometrics Laboratory"
  image: images/EML_logo_small.png
  repo-url: https://github.com/berkeley-eml/quarto-site
  site-url: https://eml.berkeley.edu
  #repo-actions: [edit, issue]
  page-navigation: true
  #bread-crumbs: true
  favicon: images/favicon.ico
  navbar:
    background: light
    logo: images/EML_logo_small.png
    logo-alt: "EML logo"
    search: true
    left:
      - text: Home
        href: index.qmd
      #- text: About
      #  href: about.qmd
      - text: Services
        href: services.qmd
      - text: Contact
        href: contact.qmd
  sidebar:
    style: "floating"
    # disabled when navbar search is on
    search: true
    collapse-level: 1
    contents:
      - section: "About"
        contents:
          - history.qmd
          - availability.qmd
          #- system-status.qmd
      - section: "Accounts"
        contents:
          - accounts.qmd
          - account-types.qmd
          - passwords.qmd
          - security.qmd
          - section: "Policies and Rules"
            contents:
              - eligibility.qmd
              - lab-rules.qmd
              - restrictions.qmd
              - rules-policies.qmd
              - rules.qmd
              - server_rules.qmd
              - copyright.qmd
          - homepage.qmd
          - ergonomics.qmd
      - section: "Remote Access"
        contents:
          - monitoring.qmd
          - jupyterhub.qmd
          - section: "Secure Shell"
            contents:
              - ssh.qmd
              - ssh-keys.qmd
              - ssh-tunnel.qmd
              - putty.qmd
          - section: "File Transfer"
            contents:
              - sftp-scp.qmd
              - globus.qmd
              - rclone.qmd
              - mount-home.qmd
          - rdp.qmd
          - vpn.qmd
          - x2go.qmd
          - x-windows.qmd
      - section: "Cluster"
        contents:
          - cluster.qmd
          - compute-servers-policy.qmd
          - grafana.qmd
          - hardware.qmd
          - servers.qmd
          - memory.qmd
          - savio.qmd
          - background.qmd
      - section: "Data and Storage"
        contents:
          - disk-quota.qmd
          - disk-space.qmd
          - file-permissions.qmd
          - emldata.qmd
          - tape-backups.qmd
      - section: "Software"
        contents:
          - software.qmd
          - python-packages.qmd
          - r-libraries.qmd
          - terminate-r.qmd
          - julia-packages.qmd
          - tensorflow.qmd
          - ucthesis.qmd
          - unix-processes.qmd
format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
