# Eligibility Policies

Who Can Use the EML:

-   Registered graduate students in the Economics Ph.D. program;
    continuing but unregistered graduate students in the Economics Ph.D.
    program who are writing dissertations; faculty in the Economics
    department; visiting scholars who are sponsored by the Economics
    department; Economics department staff and research support
    personnel.

-   Registered students who are currently enrolled in a graduate course
    that is using the EML. Class accounts are handed out by the
    instructor in class, and any registered student, graduate or
    undergraduate, who is currently enrolled in the course may have an
    EML account for that semester.

-   Others by exception, such as alumni up to two months out from the
    Ph.D. degree; courtesy accounts for software vendors; system
    administrators at related facilities; non-departmental research
    project teams. The EML has specific guidelines governing
    non-departmental research project accounts that can be obtained on
    request from the EML manager in 643 Evans Hall.

  

Any graduate, staff, or faculty user may use the workstations in 616
Evans Hall on a twenty-four hour basis, provided you have a security
card key to let you into the building during non-working hours.
