# Managing Passwords

Whenever you login, you must type both your login name and your
correspondin password. Your password serves as a security check to
protect your UNIX account from unauthorized users. Only people who know
your password can login to your account. Therefore, it is probably a
good idea to change your password on a regular basis.

To change your password, use the "passwd" command. The system will
prompt you for your old password as well as your new one. Your old
password is the one you signed on with and your new password is one of
your choice. Passwords must observe the following restrictions:

1.  ust be at least 6 characters. (If you use special \[eg: &, ^, \*,
    ?\] or non-printing \[eg: Control-T, TAB\] characters, the length
    may be as short as four characters.)
2.  Cannot contain all digits.
3.  Cannot be a login name, or a login name spelled backwards.
4.  Cannot contain any "piece" of the full-name as specified in the
    GECOS field, or the very "piece" spelled backwards.
5.  Cannot exactly match any word in the dictionary if the proposed
    password is 6 or 7 characters; if the proposed password is exactly 8
    characters, those 8 characters can not match any contiguous 8
    characters of any word in the dictionary.
6.  Can not be a dictionary word (as in rule 5) with a leading and/or
    trailing digit and/or punctuation mark. For example, do not use the
    following:
    -   dragon1
    -   3dragon
    -   4dragon2
    -   !dragon
    -   3dragon!
    -   \*dragon0
7.  Cannot contain all lower-case letters.

When you respond to the system's prompts for old and new passwords, what
you type will not be displayed on the screen.

Example for a user whose login name is "joe":

    $ passwd            
    Changing password for joe
    Old password:
    New password:
    Retype new password:
    $ 

If you type your old password correctly, set a legitimate new password,
and retype your new password without any mistakes, UNIX will return its
percent sign prompt "%", indicating that your new password is currently
in effect and the system is ready to accept subsequent UNIX commands. If
you make a mistake, UNIX will return an error message and you must begin
again. For more information on the passwd command, consult the UNIX
manual entry passwd(1).

Once you set a new password, you must type this password whenever you
login.

If you forget your password, contact the system staff to acquire a new
password which will make it possible for you to login to the system.

Students using class accounts must ask their instructor or TA to reset
their password. The system staff will not ordinarily reset class account
passwords.

