---
title: Account Rules
---

1.  Do not give out your account information to any other individual.
    Any individual found accessing another individual's account will
    have his/her account closed immediately, and this may result in
    further disciplinary action.

    -   Each individual is responsible for ALL activity associated with
        his/her account.

    -   DO NOT log into your account from another individual's account.

    -   Send mail to "manager" immediately if you suspect that someone
        has gained access to your account.

2.  Abuse of any computer account by an individual within the EML system
    or abuse of any other computer system may lead to termination of the
    individual's EML account and permanent suspension of all EML system
    privileges. Abuse of an account includes, but is not limited to:

    -   Unauthorized attempts to access accounts, files, or system
        resources.

    -   Malicious mischief of any sort.

    -   Any activity originating from a local account (on any computer
        system) that results in an official complaint being logged
        against the user.

    -   Unsolicited electronic communications with an individual who is
        not known to the user and/or the recipient.

    -   Use of electronic communications for advertising, selling,
        personal solicitations, or sending chain letters (The use of
        departmental aliases is restricted to University business).

    -   Failure to cooperate with requests of the System Staff regarding
        use of system resources.

    -   Playing of games.

    -   Repeated failure to follow posted rules.

3.  Individuals are not allowed to connect or remove computer equipment
    to or from the network connections in any room or office. An
    individual may request a connection for a personal computer and will
    be assigned a DHCP connection to use with the purple cables
    installed in offices. Attempting to attach any other computer
    equipment to an office network outlet is prohibited. This includes
    connecting switches, hubs, laptops or other computers from outside
    of the department.

    All network connections within the department are controlled by the
    EML. All network related requests for service or reports of problems
    should be directed to the EML.

4.  The contents of all accounts (including files that are owned or
    created by the user regardless of location) are subject to copyright
    laws, and all users must comply with those laws. All "original works
    of authorship" that are produced or distributed are covered by
    copyright law. An individual can not store or distribute (make
    available), in part or in whole, any item that is protected by
    copyright law without the written permission of the copyright owner.
    In order not to fall under the provisions of Senate Bill 1386, users
    are prohibited from storing/creating information that contains an
    individuals name in combination with personal information as defined
    by either a social security number, drivers license number, or
    financial/credit card number.

5.  EML accounts are not to be used for storing personal music or videos
    not directly related to course work or research. EML accounts can be
    used to transfer personal music or video files but the files must be
    removed within 48 hours.

6.  Restrictions on files located under the home directory with names
    that begin with a '.' prefix (referred to as 'dot' files):

    -   Only the owner is permitted to have "write" access to a 'dot'
        file.

    -   Dot files can not be a 'link' to a file outside of the user's
        account.

    -   A ".rhosts" file can not contain the name of any non-EML
        computer. Undergraduate class accounts are prohibited from using
        a ".rhosts" file.

7.  Limitations on the use of computer resources require that users do
    not run more that one large job on a computer at a time and do not
    run jobs on more than 8 computers simultaneously. When printing do
    not place more than 10 jobs in a printer queue. For information on
    resource usage see "help bigjobs".

8.  Remove messages from the incoming mail file after they have been
    read. Do not save messages in the incoming mail file
    (/var/mail/\[user-name\]). If the incoming mail file grows to more
    than 0.1MB the mail file will be truncated and messages older than
    30 days may be automatically deleted. Class accounts can not be used
    to subscribe to news groups, listing services, or are allowed to
    post messages to the net.

9.  Users are restricted to creating and modifying files under their
    account (home directory). With the exception of the use of the
    directory "/tmp" the placement or modification of files in any other
    location without authorization is prohibited. The /tmp directory can
    be used for temporary (one day only) storage of files. Files older
    than 24 hours will be automatically deleted, but users should remove
    their files as soon as their work has been completed (See "help
    tmp").

10. Accounts must be renewed according to the following schedule:

    -   Class accounts expire at the end of each semester and can not be
        renewed.

    -   Graduate accounts for Economics students are valid as long as
        the individual is currently enrolled. Alumni accounts are issued
        upon request to individuals who have left the Department in good
        standing and are valid for one year after separation from the
        Department. Alumni accounts can not be renewed.

    -   All other student accounts expire on Jan 1 and July 1 of each
        year and must be renewed.

    -   Guest accounts must be renewed each year by July 1 and require
        approval of the sponsoring faculty member.

    -   Faculty & visitor (associate research fellows) accounts expire
        upon termination of their appointments.

    -   Contractor accounts are valid indefinitely, as long as the
        account is in good standing.

    -   All other accounts expire on July 1 of each year and must be
        renewed.

    Requests for an extension of an account must be received within 15
    days of the account expiration date (send electronic mail to
    "manager@econ"). There is a $20 fee to recover files from an account
    that has expired. Refer to "help accounts" for more information.

11. Services requiring reimbursement for materials.

    -   Printing: Student accounts are charged $0.05/page for any
        printing above their quota established according to the
        following categories:

        -   40 pages for each lower division undergraduate class
            account.

        -   100 pages for each upper division undergraduate class
            account.

        -   160 pages for each graduate class account.[^1]

        -   40 pages/semester for each undergraduate student account.

        Contractor, research, and non-statistics UC staff accounts are
        charged for all printing and should refer to the current rate
        schedule.

        [^1]: Students enrolled in Stat 299 can have their quota increased
        to 500 pages during the period their thesis is being reviewed.

        Alumni accounts will be charged at the rate of $0.05/page for
        all printing.

    -   Media: Only the costs for the media are charged when
        transferring files to a removable media.

12. Please report any problems regarding equipment or system software to
    the EML staff by sending mail to "trouble" or by reporting the
    problem directly to either room 643 or 498/499. For
    information/questions on the use of application packages (eg. blss,
    sas, S), programming languages and libraries send mail to "consult".
    Questions/problems regarding accounts should be sent to "manager".
    Refer to "help emergency" for a list of people to contact in case of
    an emergency. 
