# Services

## Infrastructure

-   Compute
-   File storage
-   Backups and data recovery
-   Database
-   Statistical and system applications and utilities
-   Printing
-   Server room UPS and AC

## Desktop

-   Management of two computer labs (616 and 614)
-   Management of faculty workstations and printers
-   Immediate response to troubleshooting requests for hardware and
    software applications
-   Email, phone, and in person technical support

## Network and Security

-   Management of network infrastructure (105 subnet)
-   Firewall
-   SSH, SFTP, SCP
-   Globus

## Consulting and Training

-   Comprehensive and proactive technical troubleshooting and end user
    consulting for the entire installed applications software base
-   Open and approachable personal application consulting (SCF/EML
    systems staff) and access to a professional statistical consultant
    (Chris Paciorek)
-   Customized online documentation

## Software/Application Support

-   Support for widely used data analysis, statistical, database, and
    development software, e.g. Python, R, SQL, Matlab, Stata, Maple, Gauss,
    SAS, StatTransfer)
-   Support for many compilers and interpreters, C and Fortran, Perl, Python, PHP, and the
    Numerical Algorithms Group (NAG) library
-   Support for TeX/LaTeX
-   Statistical dataset conversion
-   Connectivity from personal computers, e.g. Samba, Exceed,
    SSH, SFTP, SCP, VNC, and RDP

## Data

-   Maintenance of a large Library reserve collection of books and
    manuals for supported applications software
-   Handling of sensitive data, e.g. clearances for the Bureau of Labor
    Statistics, Health and Retirement Survey, State of California
    Employment Development Department
-   Extensive data archives, where datasets are cleaned and documented,
    and accompanied by technical references, sample programs, and sample
    output, e.g., CPS, CEX, Census
-   Data storage and backup of large datasets, both public access and
    restricted, for use on the production server and for webenabled
    downloads

## Accounts

-   Personal accounts for students, faculty and staff
-   Graduate class accounts for Econ courses
-   Research project accounts that are shared by multiple users
-   No financial charges for CPU usage, file storage, or data recovery

## Web

-   Personal webpage hosting for faculty
-   Dissemination information regarding current findings on
    computationally intensive econometrics through conferences,
    symposia, short course programs, seminars and workshops funded by
    federal and private sector agencies.
